name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/wintbiit/grpcwebproxy:latest
            ghcr.io/wintbiit/grpcwebproxy:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/wintbiit/grpcwebproxy
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=grpcwebproxy
          cache-from: type=gha
          cache-to: type=gha,mode=max